Repository webanwendung-on18/effective-octo-waffle, pull requests merged in 2020-02, with the labels that each got.

#41 Feature/login
  src/components/DatabaseTests.js
  src/components/FormError.js
  src/components/Login.js
  src/components/Register.js
  src/materialUI/styles.js
  src/sass/base/_variables.scss
  src/sass/layout/_home.scss
Labels: :gear: Feature, enhancement

#50 Feature/navbar
  src/components/Navbar.js
  src/sass/base/_base.scss
Labels: enhancement

#52 Feature/recipe image upload
  src/components/CreateRecipe.js
  src/components/RecipeForm.js
Labels: enhancement

#55 Change route of home button to `/recipes`
  src/components/HTTP_404.js
Labels: enhancement

#57 Feature/search
  .firebaserc
  firebase.json
  functions/.gitignore
  functions/index.js
  functions/package-lock.json
  functions/package.json
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/DatabaseTests.js
  src/components/Feed.js
  src/components/Hits.js
  src/components/Navbar.js
  src/components/RecipeCard.js
  src/components/RefinementList.js
  src/components/Register.js
  src/components/SearchBox.js
  src/materialUI/styles.js
  src/sass/components/_Feed.scss
Labels: :gear: Feature

#59 Implement React Helmet⛑
  package-lock.json
  package.json
  src/App.js
  src/components/CreateRecipe.js
  src/components/Feed.js
  src/components/HTTP_404.js
  src/components/Login.js
  src/components/Profile.js
  src/components/Recipe.js
  src/components/RecipeReview.js
  src/components/Register.js
Labels: enhancement

#58 fix follow/edit button not showing correctly
  src/App.js
  src/components/Profile.js
Labels: :bug: Bug

#67 Feature/like 🤍
  .gitignore
  src/App.js
  src/components/Feed.js
  src/components/Recipe.js
  src/components/RecipeForm.js
  src/components/RefinementList.js
  src/sass/components/_Like.scss
  src/sass/main.scss
Labels: :gear: Feature

#71 Feature/comments
  package-lock.json
  package.json
  src/App.js
  src/components/Comment.js
  src/components/CommentList.js
  src/components/Recipe.js
  src/images/profile.jpg
Labels: :gear: Feature

#72 Final Styling?
  src/components/CreateRecipe.js
  src/components/HTTP_404.js
  src/components/RecipeForm.js
  src/components/RecipeReview.js
  src/materialUI/theme.js
  src/sass/base/_base.scss
  src/sass/base/_variables.scss
  src/sass/components/_RecipeForm.scss
Labels: enhancement

#75 Progressive Web App
  .firebase/hosting.YnVpbGQ.cache
  firebase.json
  firestore.indexes.json
  firestore.rules
  public/apple-touch-icon.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/splashscreens/ipad_splash.png
  public/splashscreens/ipadpro1_splash.png
  public/splashscreens/ipadpro2_splash.png
  public/splashscreens/ipadpro3_splash.png
  public/splashscreens/iphone5_splash.png
  public/splashscreens/iphone6_splash.png
  public/splashscreens/iphoneplus_splash.png
  public/splashscreens/iphonex_splash.png
  public/splashscreens/iphonexr_splash.png
  public/splashscreens/iphonexsmax_splash.png
  src/index.js
  src/serviceWorker.js
  storage.rules
Labels: enhancement
